const data = [
    {
      "title": "Hitler: The Rise of Evil",
      "event": "Early Life of Hitler",
      "takes_place": "1889 to 1934",
      "theatre": "Europe",
      "medium": "Two-Part Mini Series",
      "length": 179,
      "audio": "English",
      "metascore": "N/A",
      "user_reviews": 73,
      "awards": "Primetime Emmy Awards",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "The Gathering Storm (2002)",
      "event": "Churchill Prior To The War",
      "takes_place": "1934 to September 3 1939",
      "theatre": "Europe",
      "medium": "Film",
      "length": 96,
      "audio": "English",
      "metascore": 83,
      "user_reviews": 81,
      "awards": "Golden Globe, Peabody",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "The King's Speech (2010)",
      "event": "King George's Declaration of War",
      "takes_place": "October 31 1925 to September 3 1939",
      "theatre": "Europe",
      "medium": "Film",
      "length": 119,
      "audio": "English",
      "metascore": 88,
      "user_reviews": 84,
      "awards": "AA Best Picture, Actor, Director",
      "availability": "Netflix",
      "watched": "Yes"
    },
    {
      "title": "City of Life and Death (2009)",
      "event": "Rape of Nanjing",
      "takes_place": 1937,
      "theatre": "Asia",
      "medium": "Film",
      "length": 133,
      "audio": "Chinese",
      "metascore": 85,
      "user_reviews": 77,
      "awards": "",
      "availability": "Prime w/ Fandor",
      "watched": "No"
    },
    {
      "title": "April 9th (2015)",
      "event": "German Invasion of Denmark",
      "takes_place": "April 9th, 1940",
      "theatre": "Northern Front",
      "medium": "Film",
      "length": 90,
      "audio": "Danish",
      "metascore": "N/A",
      "user_reviews": 51,
      "awards": "",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "The King's Choice (2016)",
      "event": "German Invasion of Norway",
      "takes_place": "April 8th 1940 to April 10th 1940",
      "theatre": "Northern Front",
      "medium": "Film",
      "length": 133,
      "audio": "Danish",
      "metascore": 64,
      "user_reviews": 68,
      "awards": "",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "Into the White (2013)",
      "event": "Allied/Axis Interaction, Norway",
      "takes_place": "April 27, 1940 to April 29, 1940",
      "theatre": "Northern Front",
      "medium": "Film",
      "length": 104,
      "audio": "English",
      "metascore": 45,
      "user_reviews": 84,
      "awards": "",
      "availability": "YouTube (Official)",
      "watched": "Yes"
    },
    {
      "title": "Dunkirk (2017)",
      "event": "Dunkirk",
      "takes_place": "May 26 1940 to June 4 1940",
      "theatre": "Western Front",
      "medium": "Film",
      "length": 106,
      "audio": "English",
      "metascore": 94,
      "user_reviews": 83,
      "awards": "Tons of Nominations",
      "availability": "Prime w/ Cinemax",
      "watched": "Yes"
    },
    {
      "title": "Darkest Hour (2017)",
      "event": "Dunkirk, Churchill",
      "takes_place": "May 7 1940 to June 4 1940",
      "theatre": "Europe",
      "medium": "Film",
      "length": 125,
      "audio": "English",
      "metascore": 75,
      "user_reviews": 73,
      "awards": "Academy Award Best Actor",
      "availability": "Prime w/ HBO, Hulu w/ HBO, HBONOW",
      "watched": "Yes"
    },
    {
      "title": "Battle of Britain (1969)",
      "event": "Battle of Britain",
      "takes_place": "June 1940 to October 1940",
      "theatre": "Western Front",
      "medium": "Film",
      "length": 133,
      "audio": "English",
      "metascore": 63,
      "user_reviews": 79,
      "awards": "Golden Globe - Best Motion Picture Drama",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "Fateless (2005)",
      "event": "The Holocaust in Hungary",
      "takes_place": "June 1941",
      "theatre": "Europe",
      "medium": "Film",
      "length": 136,
      "audio": "English, Hungarian, German",
      "metascore": 87,
      "user_reviews": 76,
      "awards": "Nobel Prize for Literature",
      "availability": "Physical Only",
      "watched": "No"
    },
    {
      "title": "Suite Francaise (2014)",
      "event": "German Occupation of France",
      "takes_place": "June 10 1940",
      "theatre": "Europe",
      "medium": "Film",
      "length": 107,
      "audio": "English, German",
      "metascore": 63,
      "user_reviews": 68,
      "awards": "",
      "availability": "Netflix",
      "watched": "Yes"
    },
    {
      "title": "Generation War: Episode 1 (2013)",
      "event": "German Invasion of Russia",
      "takes_place": "June 1941 to December 1941",
      "theatre": "Eastern Front",
      "medium": "Three-Part Mini Series",
      "length": 90,
      "audio": "German",
      "metascore": 57,
      "user_reviews": 74,
      "awards": "Internat. Emmy - Best Mini-Series",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "Fortress of War (2010)",
      "event": "Defense of Brest Fortress",
      "takes_place": "June 21 1941 to June 26 1941",
      "theatre": "Eastern Front",
      "medium": "Film",
      "length": 180,
      "audio": "Russian",
      "metascore": "N/A",
      "user_reviews": 75,
      "awards": "2 Golden Globes, Oscar - Best Score",
      "availability": "SovietMoviesOnline",
      "watched": "No"
    },
    {
      "title": "Casablanca (1942)",
      "event": "Fleeing of European Refugees",
      "takes_place": "December 1941",
      "theatre": "Europe",
      "medium": "Film",
      "length": 102,
      "audio": "English",
      "metascore": 100,
      "user_reviews": 91,
      "awards": "Academy Award - Best Picture",
      "availability": "Archive.org, Netflix w/ VPN?",
      "watched": "Yes"
    },
    {
      "title": "Pearl Harbor (2001)",
      "event": "Pearl Harbor",
      "takes_place": "December 7th 1941 to Post-War",
      "theatre": "Pacific",
      "medium": "Film",
      "length": 183,
      "audio": "English",
      "metascore": 44,
      "user_reviews": 56,
      "awards": "MTV Movie Award - Best Action Sequence",
      "availability": "Paid Only",
      "watched": "Yes"
    },
    {
      "title": "Conspiracy (2001)",
      "event": "Wannsee Conference, Heydrich, The Holocaust",
      "takes_place": "January 20 1942",
      "theatre": "Europe",
      "medium": "Film",
      "length": 96,
      "audio": "English",
      "metascore": 100,
      "user_reviews": 86,
      "awards": "",
      "availability": "Amazon w/ HBO, HBONOW",
      "watched": "Yes"
    },
    {
      "title": "Anthropoid (2016)",
      "event": "Assassination of Heydrich",
      "takes_place": "May 27, 1942",
      "theatre": "Europe",
      "medium": "Film",
      "length": 120,
      "audio": "English",
      "metascore": 59,
      "user_reviews": 73,
      "awards": "",
      "availability": "Netflix with VPN?",
      "watched": "Yes"
    },
    {
      "title": "Battle for Sevastopol (2015)",
      "event": "Battle of Sevastopol",
      "takes_place": "October 1941 to July 1942",
      "theatre": "Eastern Front",
      "medium": "Film",
      "length": 122,
      "audio": "Russian (English Dub)",
      "metascore": "N/A",
      "user_reviews": 72,
      "awards": "",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "Midway (1976)",
      "event": "Battle of Midway",
      "takes_place": "April 18, 1942 to June 1942",
      "theatre": "Pacific",
      "medium": "Film",
      "length": 131,
      "audio": "English",
      "metascore": 48,
      "user_reviews": "N/A",
      "awards": "",
      "availability": "Prime w/ STARZ",
      "watched": "No"
    },
    {
      "title": "Lust, Caution (2007)",
      "event": "Japanese Rule of China and Shanghai",
      "takes_place": "Begins in 1938, Mostly in 1942",
      "theatre": "Asia",
      "medium": "Movie",
      "length": 158,
      "audio": "Various Forms of Chinese",
      "metascore": 61,
      "user_reviews": 66,
      "awards": "None Found",
      "availability": "Paid Only",
      "watched": "No"
    },
    {
      "title": "The Pacific: Episode 1 (2010)",
      "event": "Guadalcanal Campaign",
      "takes_place": "April 21 1942 to April 25 1942",
      "theatre": "Pacific",
      "medium": "TV Show",
      "length": 52,
      "audio": "English",
      "metascore": 86,
      "user_reviews": 77,
      "awards": "8 Primetime Emmys Include Best Miniseries",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "The Pacific: Episode 2 (2010)",
      "event": "Guadalcanal Campaign",
      "takes_place": "April 21 1942 to April 25 1942",
      "theatre": "Pacific",
      "medium": "TV Show",
      "length": 50,
      "audio": "English",
      "metascore": 86,
      "user_reviews": 77,
      "awards": "8 Primetime Emmys Include Best Miniseries",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "The Thin Red Line (1998)",
      "event": "Guadalcanal Campaign",
      "takes_place": "August 1942 to February 1943",
      "theatre": "Pacific",
      "medium": "Film",
      "length": 170,
      "audio": "English",
      "metascore": 78,
      "user_reviews": 83,
      "awards": "7 Academy Awards Nominations, Criterion Collection",
      "availability": "Prime w/ HBO, Hulu w/ HBO",
      "watched": "Yes"
    },
    {
      "title": "The Pacific: Episode 3 (2010)",
      "event": "Guadalcanal Campaign",
      "takes_place": "December 22nd 1942",
      "theatre": "Pacific",
      "medium": "TV Show",
      "length": 56,
      "audio": "English",
      "metascore": 86,
      "user_reviews": 77,
      "awards": "8 Primetime Emmys Include Best Miniseries",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "Stalingrad (2013)",
      "event": "Battle of Stalingrad",
      "takes_place": "January 1943 to February 1943",
      "theatre": "Eastern Front",
      "medium": "Film",
      "length": 131,
      "audio": "German, Russian",
      "metascore": 49,
      "user_reviews": 44,
      "awards": "",
      "availability": "Archive.org",
      "watched": "Yes"
    },
    {
      "title": "The White Rose (1982)",
      "event": "Resistance In Germany, Sophie Scholl",
      "takes_place": "February 18 1943 to February 22 1943",
      "theatre": "Germany",
      "medium": "Film",
      "length": 117,
      "audio": "German",
      "metascore": 76,
      "user_reviews": 84,
      "awards": "",
      "availability": "Amazon Prime, YouTube (Unofficial)",
      "watched": "Yes"
    },
    {
      "title": "Uprising (2001)",
      "event": "Warsaw Ghetto Uprising",
      "takes_place": "April 1943 to June 1943",
      "theatre": "Europe",
      "medium": "Two-Part Mini Series",
      "length": 151,
      "audio": "English",
      "metascore": 73,
      "user_reviews": 70,
      "awards": "Primetime Emmy for Best Stunt Coordination",
      "availability": "Paid Only",
      "watched": "Yes"
    },
    {
      "title": "Generation War: Episode 2 (2013)",
      "event": "The Holocaust",
      "takes_place": "3 Days Before Kursk",
      "theatre": "Eastern Front",
      "medium": "Three-Part Mini Series",
      "length": 90,
      "audio": "German",
      "metascore": 57,
      "user_reviews": 74,
      "awards": "International Emmy - Best Mini-Series",
      "availability": "DailyMotion (Unofficial)",
      "watched": "Yes"
    },
    {
      "title": "The Pacific: Episode 4 (2010)",
      "event": "Operation Cartwheel",
      "takes_place": "December 26th 1943 to May 1944",
      "theatre": "Pacific",
      "medium": "TV Show",
      "length": 51,
      "audio": "English",
      "metascore": 86,
      "user_reviews": 77,
      "awards": "8 Primetime Emmys Include Best Miniseries",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "Band of Brothers: Episode 1 (2001)",
      "event": "America Prepares",
      "takes_place": "July 10 1942 to June 5 1944",
      "theatre": "America",
      "medium": "TV Show",
      "length": 83,
      "audio": "English",
      "metascore": 86,
      "user_reviews": 93,
      "awards": "Seven Primetime Emmys inc. Best Mini Series",
      "availability": "Amazon Prime, HBONOW",
      "watched": "Yes"
    },
    {
      "title": "Saving Private Ryan (1998)",
      "event": "Storming of Normandy",
      "takes_place": "June 6 1944 to July 1944",
      "theatre": "Western Front",
      "medium": "Film",
      "length": 169,
      "audio": "English, German, French, Spanish",
      "metascore": 91,
      "user_reviews": 89,
      "awards": "5 Academy Awards inc. Best Director, Editing",
      "availability": "Netflix with VPN?",
      "watched": "Yes"
    },
    {
      "title": "Band of Brothers: Episode 2 (2001)",
      "event": "Storming of Normandy",
      "takes_place": "June 6 1944 to July 1944",
      "theatre": "Western Front",
      "medium": "TV Show",
      "length": 51,
      "audio": "English",
      "metascore": 86,
      "user_reviews": 93,
      "awards": "Seven Primetime Emmys inc. Best Mini Series",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "Band of Brothers: Episode 3 (2001)",
      "event": "Battle of Carentan",
      "takes_place": "June 10 1944 to June 14 1944",
      "theatre": "Western Front",
      "medium": "TV Show",
      "length": 59,
      "audio": "English",
      "metascore": 86,
      "user_reviews": 93,
      "awards": "Seven Primetime Emmys inc. Best Mini Series",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "Valkyrie (2008)",
      "event": "July 20 1944 Plot to Kill Hitler",
      "takes_place": "March 1943 to July 21 1944",
      "theatre": "Europe",
      "medium": "Movie",
      "length": 124,
      "audio": "English",
      "metascore": 56,
      "user_reviews": 63,
      "awards": "",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "The Diary of Anne Frank (1959)",
      "event": "The Holocaust",
      "takes_place": "July 1942 to August 4 1944",
      "theatre": "Europe",
      "medium": "Film",
      "length": 170,
      "audio": "English",
      "metascore": 76,
      "user_reviews": 76,
      "awards": "12 Golden Globe, Academy Award Noms",
      "availability": "Prime w/ HBO, Hulu w/ HBO",
      "watched": "Yes"
    },
    {
      "title": "The Pacific: Episode 5 (2010)",
      "event": "Battle of Peleliu",
      "takes_place": "September 15 1944",
      "theatre": "Pacific",
      "medium": "TV Show",
      "length": 49,
      "audio": "English",
      "metascore": 86,
      "user_reviews": 77,
      "awards": "8 Primetime Emmys Include Best Miniseries",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "The Pacific: Episode 6 (2010)",
      "event": "Battle of Peleliu",
      "takes_place": "September 16 1944 to September 19th 1944",
      "theatre": "Pacific",
      "medium": "TV Show",
      "length": 49,
      "audio": "English",
      "metascore": 86,
      "user_reviews": 77,
      "awards": "8 Primetime Emmys Include Best Miniseries",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "The Pacific: Episode 7 (2010)",
      "event": "Battle of Peleliu",
      "takes_place": "September 16 1944 to October 1944",
      "theatre": "Pacific",
      "medium": "TV Show",
      "length": 50,
      "audio": "English",
      "metascore": 86,
      "user_reviews": 77,
      "awards": "8 Primetime Emmys Include Best Miniseries",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "A Bridge Too Far (1977)",
      "event": "Operation Market Garden",
      "takes_place": "September 17 1944 to September 25 1944",
      "theatre": "Western Front",
      "medium": "Film",
      "length": 176,
      "audio": "English",
      "metascore": 62,
      "user_reviews": 86,
      "awards": "",
      "availability": "Amazon Prime",
      "watched": "Stopped"
    },
    {
      "title": "Band of Brothers: Episode 4 (2001)",
      "event": "Operation Market Garden",
      "takes_place": "September 18 1944 to September 20 1944",
      "theatre": "Western Front",
      "medium": "TV Show",
      "length": 59,
      "audio": "English",
      "metascore": 86,
      "user_reviews": 93,
      "awards": "Seven Primetime Emmys inc. Best Mini Series",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "Band of Brothers: Episode 5 (2001)",
      "event": "Market Garden Aftermath",
      "takes_place": "Around October 1944 to December 10th 1944",
      "theatre": "Western Front",
      "medium": "TV Show",
      "length": 55,
      "audio": "English",
      "metascore": 86,
      "user_reviews": 93,
      "awards": "Seven Primetime Emmys inc. Best Mini Series",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "Band of Brothers: Episode 6 (2001)",
      "event": "Battle of the Bulge",
      "takes_place": "December 20 1944 to January 25 1945",
      "theatre": "Western Front",
      "medium": "TV Show",
      "length": 67,
      "audio": "English",
      "metascore": 86,
      "user_reviews": 93,
      "awards": "Seven Primetime Emmys inc. Best Mini Series",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "Band of Brothers: Episode 7 (2001)",
      "event": "Battle of the Bulge Aftermath",
      "takes_place": "December 20 1944 to January 25 1945",
      "theatre": "Western Front",
      "medium": "TV Show",
      "length": 72,
      "audio": "English",
      "metascore": 86,
      "user_reviews": 93,
      "awards": "Seven Primetime Emmys inc. Best Mini Series",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "The Resistance Banker (2018)",
      "event": "The Dutch Resistance",
      "takes_place": "May 10 1940 to January 27 1945",
      "theatre": "Northern Front",
      "medium": "Film",
      "length": 123,
      "audio": "Dutch",
      "metascore": "N/A",
      "user_reviews": 81,
      "awards": "",
      "availability": "Netflix",
      "watched": "Yes"
    },
    {
      "title": "Band of Brothers: Episode 8 (2001)",
      "event": "Battle of the Bulge Aftermath",
      "takes_place": "February 5 1945 to March 1945",
      "theatre": "Western Front",
      "medium": "TV Show",
      "length": 58,
      "audio": "English",
      "metascore": 86,
      "user_reviews": 93,
      "awards": "Seven Primetime Emmys inc. Best Mini Series",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "The Pacific: Episode 8 (2010)",
      "event": "Battle of Iwo Jima",
      "takes_place": "July 3 1944 to February 19 1945",
      "theatre": "Pacific",
      "medium": "TV Show",
      "length": 56,
      "audio": "English",
      "metascore": 86,
      "user_reviews": 77,
      "awards": "8 Primetime Emmys Include Best Miniseries",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "Band of Brothers: Episode 9 (2001)",
      "event": "The Holocaust",
      "takes_place": "April 27, 1945",
      "theatre": "Western Front",
      "medium": "TV Show",
      "length": 58,
      "audio": "English",
      "metascore": 86,
      "user_reviews": 93,
      "awards": "Seven Primetime Emmys inc. Best Mini Series",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "The Zookeeper's Wife (2017)",
      "event": "The Holocaust, The Invasion of Poland",
      "takes_place": "September 1, 1939 to September 1946",
      "theatre": "Europe",
      "medium": "Film",
      "length": 126,
      "audio": "English",
      "metascore": 57,
      "user_reviews": 72,
      "awards": "",
      "availability": "Prime",
      "watched": "Yes"
    },
    {
      "title": "The Pianist (2002)",
      "event": "Invasion of Poland",
      "takes_place": "September 17 1939 to October 1945",
      "theatre": "Europe",
      "medium": "Film",
      "length": 150,
      "audio": "English",
      "metascore": 85,
      "user_reviews": 77,
      "awards": "3 Oscars, AcdAwrd Best Picture",
      "availability": "Amazon Primve",
      "watched": "Yes"
    },
    {
      "title": "Downfall (2004)",
      "event": "Final Days of Hitler",
      "takes_place": "April 16 1945 to April 30 1945",
      "theatre": "Europe",
      "medium": "Film",
      "length": 155,
      "audio": "German",
      "metascore": 82,
      "user_reviews": 86,
      "awards": "Metacritic Must-See, \"Hitler Rant\" Movie",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "Band of Brothers: Episode 10 (2001)",
      "event": "Victory in Europe",
      "takes_place": "May 8, 1945",
      "theatre": "Western Front",
      "medium": "TV Show",
      "length": 62,
      "audio": "English",
      "metascore": 86,
      "user_reviews": 93,
      "awards": "Seven Primetime Emmys inc. Best Mini Series",
      "availability": "Amazon Prime",
      "watched": "Yes"
    },
    {
      "title": "Photographer of Mauthausen",
      "event": "",
      "takes_place": "",
      "theatre": "",
      "medium": "",
      "length": "",
      "audio": "",
      "metascore": "",
      "user_reviews": "",
      "awards": "",
      "availability": "",
      "watched": ""
    },
    {
      "title": "Schindler's List (1993)",
      "event": "",
      "takes_place": "",
      "theatre": "",
      "medium": "",
      "length": "",
      "audio": "",
      "metascore": "",
      "user_reviews": "",
      "awards": "",
      "availability": "",
      "watched": ""
    },
    {
      "title": "Pacific 9",
      "event": "",
      "takes_place": "",
      "theatre": "",
      "medium": "",
      "length": "",
      "audio": "",
      "metascore": "",
      "user_reviews": "",
      "awards": "",
      "availability": "",
      "watched": ""
    },
    {
      "title": "Into the Storm",
      "event": "",
      "takes_place": "",
      "theatre": "",
      "medium": "",
      "length": "",
      "audio": "",
      "metascore": "",
      "user_reviews": "",
      "awards": "",
      "availability": "",
      "watched": ""
    },
    {
      "title": "Pacific 10",
      "event": "",
      "takes_place": "",
      "theatre": "",
      "medium": "",
      "length": "",
      "audio": "",
      "metascore": "",
      "user_reviews": "",
      "awards": "",
      "availability": "",
      "watched": ""
    }
  ]

  export default data;